### ISSUE TITLE
Automatic selection of seed points for Level Set Algorithm in ImageJ

### ISSUE THREAD

**Issue by devoworm** [devoworm/GSoC-2017#12]

**Comment by sedflix** [comment]
PlugInForLevelSet.java includes the code for the same. At the time of closing this issue, it follows the following procedure:
- Use a classifier that was made using Trainable Weka Segmentation tool
- Using that classifier, a probability map(probability for a pixel occurring inside the cell) is obtained
- Probability Map is thresholded to obtain at least some reason inside all the cells[It has been hard coded and works pretty well till now]
- At this stage, we have an ROI inside all the cells in the embryo[ideally].
- Level Sets[Active Contours] is applied to each cell individually with an aim to expand the ROI to cover up all the area in that cell

All this is performed automatically by the plugin.

Besides this several other measures have been implemented to achieve good results.
