### ISSUE TITLE
Do a "Hello World" Assignment

### ISSUE THREAD

**Issue by devoworm** [devoworm/GSoC-2017#5]

**Comment by devoworm** [comment]
Short presentation to group, group archive.

**Comment by sedflix** [comment]
Any Examples?

**Comment by devoworm** [comment]
What I have in mind for this is the 20-30 minute talk I e-mailed you about a few days ago. Schedule your time here: http://doodle.com/poll/btmdggfms5uyitsa

**Comment by sedflix** [comment]
Link to my presentation: https://docs.google.com/presentation/d/1acz2OCMLCdP4SJKuTt5yeDaLL_C9DVPfZQ4OlQrtP-A/pub?start=false&loop=true&delayms=3000
